# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Use your project's .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    # Optional: Publish artifacts
    - name: Publish
      run: dotnet publish -c Release -o ./publish

    # Optional: Upload published files as artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish